// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLIysjtCYQbXlBMso2kV7IOJzhmqsx044',
    appId: '1:612651442356:web:b8e3bb3891cc52e1b137e1',
    messagingSenderId: '612651442356',
    projectId: 'finalmobile-project',
    authDomain: 'finalmobile-project.firebaseapp.com',
    storageBucket: 'finalmobile-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsV7D5VAWxGAB8nHQqs9DetZ0jKTr2Kmk',
    appId: '1:612651442356:android:93d1e4703ae841f0b137e1',
    messagingSenderId: '612651442356',
    projectId: 'finalmobile-project',
    storageBucket: 'finalmobile-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfl5gKmR58vCZobGG8kKlho1o0YYb-gKg',
    appId: '1:612651442356:ios:06eb47eecc5a89e7b137e1',
    messagingSenderId: '612651442356',
    projectId: 'finalmobile-project',
    storageBucket: 'finalmobile-project.firebasestorage.app',
    iosClientId: '612651442356-4i84ohsa3kd480pg6utnev75in9tjg1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfl5gKmR58vCZobGG8kKlho1o0YYb-gKg',
    appId: '1:612651442356:ios:06eb47eecc5a89e7b137e1',
    messagingSenderId: '612651442356',
    projectId: 'finalmobile-project',
    storageBucket: 'finalmobile-project.firebasestorage.app',
    iosClientId: '612651442356-4i84ohsa3kd480pg6utnev75in9tjg1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLIysjtCYQbXlBMso2kV7IOJzhmqsx044',
    appId: '1:612651442356:web:6d0ec70d1c62fae9b137e1',
    messagingSenderId: '612651442356',
    projectId: 'finalmobile-project',
    authDomain: 'finalmobile-project.firebaseapp.com',
    storageBucket: 'finalmobile-project.firebasestorage.app',
  );
}
