// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using StarTEDSystem.Entities;

namespace StarTEDSystem.DAL;

internal partial class StarTEDContext : DbContext
{
    public StarTEDContext(DbContextOptions<StarTEDContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Club> Clubs { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_CI_AS");

        modelBuilder.Entity<Club>(entity =>
        {
            entity.HasKey(e => e.ClubID).HasName("PK_dbo.Clubs");

            entity.HasOne(d => d.Employee).WithMany(p => p.Clubs).HasConstraintName("FK_dbo.Clubs_dbo.Employees_EmployeeID");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeID).HasName("PK_dbo.Employees");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}